metadata:
  name: foaas-deployment
  labels:
    app: foaas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foaas
  template:
    metadata:
      labels:
        app: foaas
    spec:
      containers:
      - name: foaas
        image: pincher95/foaas:3
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: foaas-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: LoadBalancer
spec:
  type: LoadBalancer
  selector:
    app: foaas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
