apiVersion: apps/v1
kind: Deployment
metadata:
  name: foaas-deploy
  labels:
    app: foaas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foaas
  template:
    metadata:
      labels:
        app: foaas
    spec:
      containers:
        - name: foaas-pod
          image: pincher95/foaas:latest
          labels:
            name: foaas-pod
          ports:
            - name: http
              protocol: TCP
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: foaas-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: LoadBalancer
spec:
  type: LoadBalancer
  selector:
    app: foaas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80